target 'FDB', :exclusive => true do
  pod "FDB", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "FDB", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end

post_install do |installer|
    installer.project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['FRAMEWORK_SEARCH_PATHS'] = [ '$(PLATFORM_DIR)/Developer/Library/Frameworks' ]
        end
    end
end